version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-container
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 12345

volumes:
  mysql-data:
    external: true